export * from './palletController.service';
import { PalletControllerService } from './palletController.service';
export * from './palletPalletTypeController.service';
import { PalletPalletTypeControllerService } from './palletPalletTypeController.service';
export * from './palletStockController.service';
import { PalletStockControllerService } from './palletStockController.service';
export * from './palletTypeController.service';
import { PalletTypeControllerService } from './palletTypeController.service';
export * from './pingController.service';
import { PingControllerService } from './pingController.service';
export * from './productController.service';
import { ProductControllerService } from './productController.service';
export * from './stockController.service';
import { StockControllerService } from './stockController.service';
export * from './stockPalletController.service';
import { StockPalletControllerService } from './stockPalletController.service';
export * from './stockProductController.service';
import { StockProductControllerService } from './stockProductController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [PalletControllerService, PalletPalletTypeControllerService, PalletStockControllerService, PalletTypeControllerService, PingControllerService, ProductControllerService, StockControllerService, StockPalletControllerService, StockProductControllerService, UserControllerService];
