/**
 * wms-lb4-poc-api
 * WMS Loopback 4 PoC API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Partial<PalletType>, schemaOptions: { partial: true })
 */
export interface PalletTypePartial { 
    /**
     * Pallet type indentifier
     */
    id?: string;
    /**
     * Pallet Type name
     */
    name?: string;
    /**
     * Pallet Type length in mm
     */
    length?: number;
    /**
     * Pallet Type width in mm
     */
    width?: number;
    /**
     * Pallet Type weight in Kg
     */
    weight?: number;
}

